// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greetings.proto

/*
Package greeterpb is a generated protocol buffer package.

It is generated from these files:
	greetings.proto
	service.proto

It has these top-level messages:
	Greeting
	Time
	GreetRequest
	GreetResponse
*/
package greeterpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Greeting struct {
	GreeterName string `protobuf:"bytes,1,opt,name=GreeterName" json:"GreeterName,omitempty"`
	Greeting    string `protobuf:"bytes,2,opt,name=Greeting" json:"Greeting,omitempty"`
	Time        *Time  `protobuf:"bytes,3,opt,name=Time" json:"Time,omitempty"`
}

func (m *Greeting) Reset()                    { *m = Greeting{} }
func (m *Greeting) String() string            { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()               {}
func (*Greeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Greeting) GetGreeterName() string {
	if m != nil {
		return m.GreeterName
	}
	return ""
}

func (m *Greeting) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *Greeting) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

type Time struct {
	UnixTime int64 `protobuf:"varint,1,opt,name=UnixTime" json:"UnixTime,omitempty"`
}

func (m *Time) Reset()                    { *m = Time{} }
func (m *Time) String() string            { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()               {}
func (*Time) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Time) GetUnixTime() int64 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greeter.greetings.Greeting")
	proto.RegisterType((*Time)(nil), "greeter.greetings.Time")
}

func init() { proto.RegisterFile("greetings.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2f, 0x4a, 0x4d,
	0x2d, 0xc9, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x04, 0x0b, 0xa4,
	0x16, 0xe9, 0xc1, 0x25, 0x94, 0x4a, 0xb9, 0x38, 0xdc, 0xa1, 0x1c, 0x21, 0x05, 0x2e, 0x6e, 0x77,
	0x88, 0x02, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x64, 0x21, 0x21,
	0x29, 0x84, 0x6a, 0x09, 0x26, 0xb0, 0x34, 0x42, 0xb7, 0x36, 0x17, 0x4b, 0x48, 0x66, 0x6e, 0xaa,
	0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb8, 0x1e, 0x86, 0x5d, 0x7a, 0x20, 0xe9, 0x20, 0xb0,
	0x22, 0x25, 0x25, 0x88, 0x62, 0x90, 0x81, 0xa1, 0x79, 0x99, 0x15, 0x60, 0x8d, 0x20, 0xfb, 0x98,
	0x83, 0xe0, 0x7c, 0x27, 0xee, 0x28, 0x4e, 0xa8, 0x19, 0x05, 0x49, 0x49, 0x6c, 0x60, 0x1f, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x21, 0x44, 0xd8, 0xd4, 0x00, 0x00, 0x00,
}
